package bot.fsm;

public enum UserState {
    DEFAULT,
    // Notes
    AWAITING_NOTE_NAME_TO_ADD,
    AWAITING_NOTE_TEXT,
    AWAITING_NOTE_NAME_TO_EDIT,
    AWAITING_NOTE_NEW_NAME,
    AWAITING_NOTE_NEW_TEXT,
    AWAITING_NOTE_NAME_TO_SHOW,
    AWAITING_NOTE_NAME_TO_REMOVE,
    // Reminders
    AWAITING_REMINDER_NAME_TO_ADD,
    AWAITING_REMINDER_TEXT,
    AWAITING_ONCE_DATE,
    AWAITING_RECURRING_DAYS,
    AWAITING_REMINDER_NAME_TO_EDIT,
    AWAITING_REMINDER_NEW_NAME,
    AWAITING_REMINDER_NEW_TIME,
    AWAITING_REMINDER_NAME_TO_REMOVE,
    AWAITING_REMINDER_NAME_TO_SHOW,
    // TimeZone
    AWAITING_TIMEZONE_OFFSET
}