package bot.fsm;

public enum UserState {
    DEFAULT,
    AWAITING_NOTE_NAME_ADD,
    AWAITING_NOTE_TEXT_ADD,
    AWAITING_NOTE_NAME_EDIT,
    AWAITING_NOTE_TEXT_EDIT,
    AWAITING_NOTE_NAME_SHOW,
    AWAITING_NOTE_NAME_REMOVE
}